version: "3.4"

services:
    web-example:
        build:
            context: .
        expose:
            - 5000
        volumes:
            - .:/app:ro
        command: /usr/local/bin/gunicorn -k gevent --reload --workers 10 --worker-connections 10 --access-logfile=- --pythonpath /app -b :5000 app:app
        environment: 
            CLUSTER_URL: https://test-travelplanner-ov11dgo0.weaviate.network

    weaviate:
        command:
            - --host
            - 0.0.0.0
            - --port
            - '8081'
            - --scheme
            - http
        image: cr.weaviate.io/semitechnologies/weaviate:1.24.1
        ports:
            - 8081:8081
            - 50052:50052
        volumes:
            - weaviate_data:/var/lib/weaviate
        restart: on-failure:0
        environment:
            QUERY_DEFAULTS_LIMIT: 25
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
            PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
            DEFAULT_VECTORIZER_MODULE: 'none'
            ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
            CLUSTER_HOSTNAME: 'node1'

    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "8008:8081"
        volumes:
            - ./static:/www/static:ro
            - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web-example
            - weaviate

volumes:
  weaviate_data: